org: mellomaths
app: aws-node-http-serverless-api
service: aws-node-http-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}

functions:
  createCustomer:
    handler: src/customers/createCustomer.handle
    events:
      - httpApi:
          path: /customers
          method: post

  getCustomers:
    handler: src/customers/getCustomers.handle
    events:
      - httpApi:
          path: /customers
          method: get

  healthCheck:
    handler: src/health-check/healthCheck.handle
    events:
      - httpApi:
          path: /health
          method: get

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}

plugins:
  - serverless-offline
